# SPDX-License-Identifier: Apache-2.0
# West YAML manifest for Zephyr as Xen Dom0

manifest:
  self:
    path: zephyr-dom0-xt

  remotes:
    - name: firscity
      url-base: https://github.com/firscity/
    - name: lorc
      url-base: https://github.com/lorc/
    - name: zephyr
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: firscity
      revision: zephyr_aos_porting
      west-commands: scripts/west-commands.yml
    - name: zephyr-xenlib
      remote: lorc
      revision: initial
    - name: littlefs
      remote: zephyr
      path: modules/fs/littlefs
      groups:
        - fs
      revision: 9e4498d1c73009acd84bb36036ee5e2869112a6c